version: '3'
services:
  web:
    build:
      context: ./service
      dockerfile: Dockerfile
    image: yagrariksa/dump-git:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
