name: Build and Push Docker Compose Services

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Read version from VERSION file
      id: read_version
      run: echo ::set-output name=VERSION::$(cat VERSION)

    - name: Build and Push Docker Compose
      env:
        APP_VERSION: ${{ steps.read_version.outputs.VERSION }}-${{ github.run_number }}
      run: |
        docker-compose build
        docker-compose push
        docker tag yagrariksa/dump-git:latest yagrariksa/dump-git:$APP_VERSION
        docker push yagrariksa/dump-git:$APP_VERSION

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git clone https://github.com/your-username/your-repo.git ~/dump-git
            cd ~/dump-git
            docker-compose pull web
            docker-compose up -d
